### ISSUE TITLE
SuperLoader.py fails

### ISSUE THREAD

**Issue by luis605** [MaxwellSalmon/Omicron35#1]
Hello there! When I start the game I get an AttributeError in SuperLoader.py file. It says that NoneType has not attribute .filename

`python

Changing textures
Traceback (most recent call last):
  File "C:\Users\Acer\Downloads\Omicron35-master\Omicron35-master\main.py", line 123, in <module>
    app = MyApp()
  File "C:\Users\Acer\Downloads\Omicron35-master\Omicron35-master\main.py", line 24, in __init__
    self.superloader.load(settings.environment, True)
  File "C:\Users\Acer\Downloads\Omicron35-master\Omicron35-master\superloader.py", line 51, in load
    self.change_textures()
  File "C:\Users\Acer\Downloads\Omicron35-master\Omicron35-master\superloader.py", line 190, in change_textures
    old_time = self.determine_texture_time()
  File "C:\Users\Acer\Downloads\Omicron35-master\Omicron35-master\superloader.py", line 179, in determine_texture_time
    path = str(base.scene.find('**/+GeomNode').findTexture('*').filename)
AttributeError: 'NoneType' object has no attribute 'filename'`

**Comment by MaxwellSalmon** [comment]
Thanks a lot! I will look into this and fix it as soon as possible :-)

**Comment by luis605** [comment]
Thanks :-)

**Comment by luis605** [comment]
We also need to edit the .prc files because the: 

Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
:display:windisplay(warning): SetForegroundWindow() failed!
:gobj(error): Texture::read() - couldn't read: maps/snow.png
:gobj(error): Unable to find texture "maps/snow.png" on model-path /c/Users/Acer/Downloads/Omicron35-master;/c/Users/Acer/AppData/Local/Programs/Python/Python39/Lib/site-packages/panda3d/etc/..;/c/Users/Acer/AppData/Local/Programs/Python/Python39/Lib/site-packages/panda3d/etc/../models
:ParticleEffect(warning): loadConfig: failed to load particle file: 'particles/light_window_snow.ptf'
Traceback (most recent call last):
  File "c:\Users\Acer\Downloads\Omicron35-master\main.py", line 123, in <module>
    app = MyApp()
  File "c:\Users\Acer\Downloads\Omicron35-master\main.py", line 20, in __init__
    self.weather = weather.Weather()
  File "c:\Users\Acer\Downloads\Omicron35-master\weather.py", line 26, in __init__
    snow.loadConfig(wsnowpath)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\direct\particles\ParticleEffect.py", line 208, in loadConfig
    exec(data)
  File "<string>", line 30, in <module>
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\direct\particles\SpriteParticleRendererExt.py", line 45, in addTextureFromFile
    return self.setTextureFromFile(fileName)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\direct\particles\SpriteParticleRendererExt.py", line 34, in setTextureFromFile
    t = loader.loadTexture(fileName)
  File "C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\direct\showbase\Loader.py", line 756, in loadTexture
    raise IOError(message)
OSError: Could not load texture: maps/snow.png

**Comment by MaxwellSalmon** [comment]
I suspect the error is due to some hardcoded file paths. I will test it on another system when I have the time. It should be easier to identify the paths. Thanks for noticing me!

**Comment by luis605** [comment]
No problem.
