### ISSUE TITLE
main.py Fails

### ISSUE THREAD

**Issue by ghost** [MaxwellSalmon/Omicron35#2]
Traceback (most recent call last):
  File "C:\Py\o35\Omicron35\main.py", line 123, in <module>
    app = MyApp()
  File "C:\Py\o35\Omicron35\main.py", line 25, in __init__
    self.superloader.load(settings.environment, True)
  File "C:\Py\o35\Omicron35\superloader.py", line 56, in load
    self.change_textures()
  File "C:\Py\o35\Omicron35\superloader.py", line 213, in change_textures
    old_time = self.determine_texture_time()
  File "C:\Py\o35\Omicron35\superloader.py", line 202, in determine_texture_time
    path = str(base.scene.find('**/+GeomNode').findTexture('*').filename)
AttributeError: 'NoneType' object has no attribute 'filename'

[process exited with code 1]

**Comment by MaxwellSalmon** [comment]
Thank you! I am aware of this issue and it is most likely due to hardcoded file paths. I will fix it at some point, but it is low priority at the moment.

**Comment by ghost** [comment]
Thank you for your reply, only a few people actually respond to these bug
reports

**Comment by ghost** [comment]
Hey, I'm a very fan of yours. Can we collaborate?
We are Zanvok Corporation.

Hope you reply soon....

**Comment by MaxwellSalmon** [comment]
What do you have in mind?

**Comment by ghost** [comment]
Actually we are a really *SMALL* software company making operating system
and other software, it would be really nice if you collaborate with us..!
We started this company in 2018, and we are only three members , 16 years
of age...

**Comment by MaxwellSalmon** [comment]
But what collaboration are you thinking of?

**Comment by ghost** [comment]
I mean, im not forcing you, Im just asking will you join our company??
I'm sad but since me and my fellow company member are small yet to earn so
we can't pay you..!

**Comment by MaxwellSalmon** [comment]
No thank you. I already have a job.

**Comment by ghost** [comment]
Ok, no problem, thanks for reply..
